import type { Metadata } from "next"
import "@/src/styles/globals.css"
import { Inter } from "next/font/google"

import { AntdRegistry } from "@ant-design/nextjs-registry"

import HeaderMenu from "../components/HeaderMenu"
import Container from "../components/Container"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <>
            <HeaderMenu />
            {/* <Header /> */}
            <Container>{children}</Container>
          </>
        </AntdRegistry>
      </body>
    </html>
  )
}
